defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: ckeditor_development

test:
  <<: *defaults
  database: ckeditor_test

production:
  <<: *defaults
  database: ckeditor_development
